// Prompt banks. Edit freely — or drop your own into prompts.custom.json (see README).
// Use <BLANK> anywhere you want the UI to render a fill-in-the-blank slot.

export const MAIN_PROMPTS = [
  "The worst possible thing to shout during a moment of silence",
  "A terrible name for a cruise ship",
  "The real reason the dinosaurs went extinct",
  "A rejected slogan for a cough syrup",
  "Something you should never say to your boss on a Monday",
  "The most useless superpower imaginable",
  "A bad excuse for being three hours late to your own wedding",
  "The title of the world's most boring documentary",
  "What aliens would say after five minutes of watching Earth",
  "A terrible thing to find in your hotel minibar",
  "The worst possible first line of a wedding speech",
  "An awful name for a new brand of energy drink",
  "Something you'd hate to hear your surgeon say",
  "The secret ingredient in grandma's famous casserole",
  "A rejected Olympic sport",
  "What your pet is definitely thinking about you",
  "The worst way to answer a video call",
  "A terrible motivational poster caption",
  "The most unsettling thing to find written inside a library book",
  "A bad name for a hair salon",
  "What the last text message on Earth will say",
  "The worst possible theme for a children's birthday party",
  "An unconvincing alibi",
  "A terrible new flavour of ice cream",
  "Something you'd never want to hear coming from the attic",
  "The worst possible name for a guard dog",
  "A rejected ride at a theme park",
  "What your smart speaker says when it finally snaps",
  "The worst gift to receive from your in-laws",
  "A terrible thing to be famous for",
  "The most disappointing thing to find at the end of a rainbow",
  "An awful piece of advice to give a nervous groom",
  "Something that should never be sold in a vending machine",
  "The worst possible name for a submarine",
  "A rejected reality TV show about accountants",
  "What you'd carve into your gravestone to confuse future archaeologists",
  "The worst thing to whisper during a hug",
  "A terrible name for a coffee shop",
  "The most suspicious thing to order at a fancy restaurant",
  "An unhelpful thing to say in a hostage negotiation",
  "The worst possible ringtone for a funeral director",
  "A new low in airline seating",
  "Something you'd regret teaching a parrot",
  "The worst possible tattoo to get in a foreign language",
  "A rejected name for a sports team",
  "What's definitely in the office fridge right now",
  "The worst possible wifi network name for a hospital",
  "A terrible thing to be sponsored by",
  "The real reason your neighbour hasn't spoken to you in a year",
  "An awful topic for a TED talk",
  "Something you'd never want printed on a doctor's business card",
  "The worst possible way to start a job interview",
  "A terrible name for a haunted house attraction",
  "What the group chat is saying about you right now",
  "The most unnecessary item in a survival kit",
  "A rejected Disney sidekick",
  "The worst possible headline to wake up to",
  "An unwise thing to microwave",
  "Something you'd hate to see on a restaurant health inspection report",
  "The worst possible username for a bank employee",
  "A terrible new rule for public transport",
  "What a haunted GPS would say",
  "The worst possible name for a nursery school",
  "An awful thing to find in your grandparents' basement",
  "The least romantic possible place to propose",
  "A rejected name for a perfume",
  "Something you should never bring to a job you've had for ten years",
  "The worst possible thing to be good at",
  "A terrible name for a yoga studio",
  "What the intern definitely did to the printer",
  "The most alarming thing your car could start doing",
  "An awful item to smuggle through airport security",
  "Something you'd never want to hear your dentist humming",
  "The worst possible slogan for a new country",
  "A rejected flavour of toothpaste",
  "What you'd say to your teenage self to ruin their day",
  "The worst possible name for a cat",
  "A terrible new feature for social media",
  "Something that would instantly ruin a picnic",
  "The most upsetting thing to find in a piñata",
  "An awful nickname to be stuck with at work",
  "The worst possible thing to be allergic to",
  "A rejected superhero origin story",
  "What the ghost in your house is annoyed about",
  "The worst possible name for a wedding band",
  "A terrible thing to say while being photographed",
  "Something you'd hate to find in the back of a taxi",
  "The most useless thing to invent in the year 3000",
  "An awful way to be woken up",
  "The worst possible thing to name a hurricane",
  "A rejected breakfast cereal mascot",
  "What your search history says about you",
  "The worst possible place to fall asleep",
  "A terrible thing to keep in your desk drawer",
  "Something no one should do at a buffet",
  "The most unconvincing thing to be an 'expert' in",
  "An awful piece of gym equipment",
  "The worst possible name for a law firm",
  "What the last person to leave the party did",
  "A terrible thing to be remembered for at school reunions",
  "The most unhinged item on someone's bucket list",
  "An awful way to signal you want to leave a conversation",
  "The worst possible thing to bring to a potluck",
  "A rejected name for the next Mars rover",
  "Something you'd never want your parents to walk in on you doing",
  "The worst possible thing to be handed at a wedding",
  "A terrible name for a security company",
  "What the vending machine in a haunted office dispenses",
  "The most passive-aggressive thing to leave on a sticky note",
  "An awful thing to shout at a sports match",
  "The worst possible euphemism for getting fired",
  "A terrible thing to charge extra for",
  "Something you'd hate to hear on the intercom mid-flight",
  "The worst possible name for a bakery",
  "What the cat knocked off the counter this time, and why",
  "A rejected emoji nobody needed",
  "The worst possible thing to be an 'influencer' for",
  "An awful thing to find in a used car's glovebox",
  "The most cursed sandwich combination",
  "A terrible thing to do on the first day of a new job",
  "The worst possible name for a retirement home",
  "Something that should absolutely not be a competitive sport",
  "An awful way to end a text to your boss"
];

// Everyone answers the same prompt in the final round. Fill-in-the-blank style works great here.
export const FINAL_PROMPTS = [
  "The five-star review for the world's worst hotel: <BLANK>",
  "The warning label they should put on human beings: <BLANK>",
  "Breaking news: local man arrested for <BLANK>",
  "The one house rule that must never be broken: <BLANK>",
  "My autobiography will be called <BLANK>",
  "The real fine print at the bottom of every contract: <BLANK>",
  "A new national holiday that celebrates <BLANK>",
  "The message in the bottle washed up after 200 years read: <BLANK>",
  "Scientists have finally proven that <BLANK>",
  "The last thing the world's unluckiest person said was <BLANK>",
  "Instead of a handshake, the new polite greeting is <BLANK>",
  "The most honest slogan a government could ever use: <BLANK>",
  "Archaeologists in the year 4000 will conclude that we worshipped <BLANK>",
  "The sequel nobody asked for: <BLANK> 2",
  "New law passed today: it is now illegal to <BLANK>",
  "The one thing they don't tell you about growing up: <BLANK>",
  "My superhero name is Captain <BLANK>",
  "The title of the saddest song ever written: <BLANK>",
  "Found in a time capsule from today: <BLANK>",
  "The world would be a much better place if everyone just <BLANK>"
];

// Used when a player runs out of time without submitting anything.
export const SAFETY_QUIPS = [
  "I panicked and wrote this instead",
  "My phone died, blame my phone",
  "Something much funnier than this",
  "[thoughtful silence]",
  "Whatever the other person wrote, but worse",
  "I was busy thinking about lunch",
  "A really long pause and then nothing",
  "This is a cry for help",
  "Pretend I said something clever",
  "I'll get the next one, I promise",
  "Vote for me anyway",
  "Technical difficulties, please stand by"
];

export function shuffle(arr, rand = Math.random) {
  const a = arr.slice();
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(rand() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}
